### ISSUE TITLE
Jetson TX2 CUDA TOOLKIT ROOT DIR Error 

### ISSUE THREAD

**Issue by james-sungjae-lee** [kookmin-sw/2019-cap1-2019_4#11]
Jetson TX2 를 TX1 과 동일하게 세팅한 다음, Jetson-Inference 깃의 튜토리얼을 진행하던 중

jetson-inference/build 디렉토리에서 cmake ../ 명령어를 쳤을 때 다음과 같은 에러가 발생하였다.

CUDA_TOOLKIT_ROOT_DIR not found or specified

그 이후, make 를 통해 다양한 camera / console 프로그램을 build 하는 과정에서 makefile 이 존재하지 않아 문제가 생긴다.

이에 대한 근본적 해결책은 CUDA TOOLKIT 의 디렉토리를 확인하고 cmake 명령어를 에러 없이 실행시키는 것이다.

**Comment by HSOOJ** [comment]
error 내용
![jetson error](https://user-images.githubusercontent.com/20984428/54084082-a169b100-436f-11e9-83e7-705313cf2b16.png)

**Comment by HSOOJ** [comment]
Jetson TX2 에 Jetpack 재설치 중 CUDA cannot be installed ~ may be caused by other apt-get command running 문제의 발생
- https://devtalk.nvidia.com/default/topic/993713/jetson-tx1/error-cuda-cannot-be-installed-on-device-/
- Jetpack 실행 파일의 priority 가 높아 발생하는 문제로 보이며, `chmod 711 JetPack-L4T-2.3.1-linux-x64.run` 을 통해 보안 수준을 바꾸어 문제를 해결해볼 수 있겠음 ( 또는 Reference 와 동일하게 chmod +x 를 이용함 )
---
JetPack 에서의 일부에서만 Progress 작동하는 원인의 파악
>Install On Target 에서만 특정한 Action 이 작동하며, Progress 가 진행되는데
>이는 상단의 사항들은 Host PC 의 Installation 상황으로 한 번만 설치되면 그 후로는 추가 설치가 필요없기 때문
>Install On Target 의 부분들은 Jetson TX2 에 설치되는 사항이므로 매번 설치 필요

**Comment by HSOOJ** [comment]
작업중 새롭게 Determining the ip address of target 에러 발생
ethernet connection 과정에서 TX2 와 Host PC 두 가지 모두 선택하는 창이 떴는데,
이러한 이유로 해당 에러가 발생한 것과 관련이 있을지 모름

ethernet 이 한 번 연결되고 나면 해당 ethernet 에 대한 정보가 남아 쌓이게 됨
이로 인해 어떤 ethernet 이 현재 연결된 상태인지 확인할 수 없는 상황이 발생

network 연결을 정확하게 확인한 다음 다시 시도해볼 필요 있음
에러와 관련된 링크
- https://devtalk.nvidia.com/default/topic/1025988/jetson-tx2/tx2-target-installation-stopped-in-quot-determining-the-ip-address-of-target-quot-/

---
Jetpack 의 설치 과정에서 CUDA-Toolkit 을 TX2 내부에서 `sudo apt-get install cuda-toolkit-9-0` 으로 수동설치하는 것으로 해결 완료.
초기에도 동일한 수동 설치가 이루어졌음에도 작동하지 않았던 이유는 정확하게 밝혀내지 못함.
