### ISSUE TITLE
feature생성 과정에서 발생하는 문제

### ISSUE THREAD

**Issue by Jisoo-Min** [kookmin-sw/2019-cap1-2019_4#14]
feature를 생성하면서 발생하는 문제들 공유

**Comment by wldud8463** [comment]
구매자가 해당 제품을 몇번 구매하는지 count 하는 변수 quantity를 만드는데 while문이 너무 오래걸림. 반복문을 사용하지 않을 방법이 필요.
<img width="1124" alt="스크린샷 2019-03-12 오후 1 02 24" src="https://user-images.githubusercontent.com/48198249/54173976-86aa5000-44c7-11e9-941d-ab50a9a67fd3.png">

**Comment by Jisoo-Min** [comment]
`num_product_per_user = pd.DataFrame({'count' : prior_and_orders.groupby( [ "user_id", "product_id"] ).size()}).reset_index()`

이런식으로 groupby해서 하면 유저 당 product 몇 번 구매했는지 나온다!!

**Comment by aaa0265** [comment]
상품에대해 재구매를 했는지 찾아내기위해 
![days-since-prior-order](https://user-images.githubusercontent.com/26623522/54810709-1e7b1b80-4cca-11e9-91c4-8e95cdc96b30.png)
이 코드를 사용하였는데 데이터를 분석해보니 상품에 대한 재구매 기록을 뜻하는 것이 아닌 해당 유저가 다시 쇼핑을 하기까지의 기간을 뜻하는 것이었다. 

재구매 여부를 확실하게 알 수 있는 것은 reordered이기 때문에, 코드를 아래처럼 수정하였다.
![reordered](https://user-images.githubusercontent.com/26623522/54812656-f6da8200-4cce-11e9-9586-6fbad777293f.png)

**Comment by aaa0265** [comment]
multi-index 형태의 DataFrame를 다룰 때 index와 column로 원하는 데이터를 뽑아내는 것에 어려움이 있다.
https://www.somebits.com/~nelson/pandas-multiindex-slice-demo.html
위 링크를 참고하면 도움이 된다.

**Comment by aaa0265** [comment]
1. dataframe에서 index가 여러개라면 multi-index

2. index를 column으로 바꾸는 과정이 필요했다. 필요한 index부분을 series로 뽑아내서 dataframe에 새로운 column을 만들고 series를 넣는 방법을 구현했다.
![line3](https://user-images.githubusercontent.com/26623522/54887918-68871b80-4edb-11e9-9ba0-1bb154f64203.png)

3. 2번 방법에 비해 쉬운 방법은 reset_index를 사용하는 것이다!!
![reset_index](https://user-images.githubusercontent.com/26623522/54887973-0f6bb780-4edc-11e9-84d4-26b5fe9cec61.png)
